### ISSUE TITLE
MicroPython v1.0

### ISSUE THREAD

**Issue by microbit-carlos** [pddring/createwithcode#2]
Hi,

First of all, I just wanted to say how awesome the Create With Code editor is, and also great work on the micro:bit simulator!

I notice this editor still uses MicroPython v0.9. In case you were not aware, there has been a [motion sensor change](https://support.microbit.org/en/support/solutions/articles/19000087020-micro-bit-motion-sensor-hardware-change) on a new minor revision of the micro:bit and we've updated the DAL and MicroPython to support the new sensors.

You can easily update the MicroPython hex and everything else should work the same. This support article contains information about how to update editors: https://support.microbit.org/solution/articles/19000084312-micro-bit-motion-sensor-hardware-changes-for-editor-developers/en

We also recommend signing up to the 'Device and DAL' mailing list, as we'll use it in the future to update editor developers of any changes that might affect them: http://eepurl.com/dyRx-v

Happy holidays!
Carlos

**Comment by pddring** [comment]
Hi Carlos,
Thanks for getting in touch. Merry Christmas to you too and thanks for all your hard work on all things micro:bit!

Thanks for letting me know - I've updated create.withcode.uk to MicroPython 1.0.1 and signed up to receive updates.

All the best,
Pete
